# Generated by Django 4.2.4 on 2023-08-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
