# Generated by Django 4.2.4 on 2023-08-18 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('douban_search', '0004_alter_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='keywords',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='douban_search.keyword'),
        ),
    ]
