# Generated by Django 4.2.4 on 2023-08-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban_search', '0010_rename_name_movie_name1_movie_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='keywords',
        ),
        migrations.AddField(
            model_name='movie',
            name='keywords',
            field=models.ManyToManyField(null=True, to='douban_search.keyword'),
        ),
    ]
