# Generated by Django 4.2.4 on 2023-08-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban_search', '0011_remove_movie_keywords_movie_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='keywords',
            field=models.ManyToManyField(to='douban_search.keyword'),
        ),
    ]
