# Generated by Django 4.2.4 on 2023-08-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban_search', '0012_alter_movie_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='emotion',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
