# Generated by Django 4.2.4 on 2023-08-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban_search', '0014_keyword_emotion_keyword_keyword2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='emotion',
            field=models.FloatField(null=True),
        ),
    ]
